using ABC_Traders.ApplicationClass;
using ABC_Traders.CommonClass;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.StartPanel;

namespace ABC_Traders
{
    public partial class loginPage : Form
    {
        //the LoginClass is stored in the login_function object
        //LoginClass login_function = new LoginClass();
        public loginPage()
        {
            InitializeComponent(); //this method is generated by the Visual Studio designer and is responsible for initializing the components
                                   //(UI controls) of the loginPage. It is often found in Windows Forms or WPF applications.
            LoginClass.LoginSuccessful += HandleLoginSuccessful; //the HandleLoginSuccessful method to the LoginSuccessful event of the LoginClass.
        }

        private void loginBtn_Click(object sender, EventArgs e)
        {
            //from the username textbox the entered value store in the username variable
            string username = usernameTextBox.Text;

            //from the password textbox the entered value store in the username variable
            string password = passwordTextBox.Text;

            LoginClass.PerformLogin(username, password); //PerformLogin Method will execute


        }

        private void HandleLoginSuccessful(string userRole)
        {
            // Logic to show the appropriate dashboard based on the user role
            switch (userRole)
            {
               //when the userRole is admin the adminMenu page will open 
                case "admin":
                    adminDashboardLoad adminMenu = new adminDashboardLoad();
                    adminMenu.Show();
                    this.Hide();
                    break;
               //when the userRole is customer the customerMenu page will open 
                case "customer":
                    customerDashboard customerMenu = new customerDashboard();
                    customerMenu.Show();
                    this.Hide();
                    break;
                //the userRole is does not match with admin and customer the invalid message will execute
                default:
                    MessageBox.Show("Invalid role");
                    break;
            }
        }

        private void signBtn_Click(object sender, EventArgs e)
        {
            customerRegistration new_account = new customerRegistration();
            this.Hide();
            new_account.Show();
        }

        private void passwordTextBox_TextChanged(object sender, EventArgs e)
        {
            LoginClass.password = passwordTextBox.Text;
        }
    }
}

